version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.1.0

jobs:
  check-dir:
    docker:
      - image: cimg/node:24.0.1
    steps:
      - checkout
      - run:
          name: Check directory
          command: |
            pwd
            ls -al

workflows:
  setup1:
    jobs:
      - check-dir
      - continuation/continue:
          configuration_path: ./circleci/continue.yml
